version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=dynamodb,ses