name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          path: ~/go/pkg/mod
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .